### PR TITLE
Fix bug when given inf objective value

### LINKED ISSUE #108: Dashboard doesn't load if any of the trials have "Infinity" values
# Bug reports

In an Optuna study, if any of the trials returns Infinity (Inf) values, the dashboard does not load, a message saying "Failed to fetch study <study_id>" is shown on the lower left corner of the dashboard

## Expected Behavior

Ignore the Infinity values and show the dashboard for other values.

## Current Behavior and Steps to Reproduce

Open a study which has Inf values in at least one trial.

image

image

I tried accessing the API at /api/studies/<study_id>, which shows some Inf values, e.g. ... "values": [Infinity] ...

Other studies which do not have Inf values, load and work as expected.

## Context
Please provide any relevant information about your setup.
This is important in case the issue is not reproducible except for under certain conditions.

  * `python -c 'import optuna; print(optuna.__version__)'`: 2.8.0
  * `optuna-dashboard --version`: 0.4.2

### PR DESCRIPTION
**Pull request by c-bata**
## Contributor License Agreement

This repository (``optuna-dashboard``) and [Goptuna](https://github.com/c-bata/goptuna) share common code.
This pull request may therefore be ported to Goptuna.
Make sure that you understand the consequences concerning licenses and check the box below if you accept the term before creating this pull request.

* [x] I agree this patch may be ported to [Goptuna](https://github.com/c-bata/goptuna) by other Goptuna contributors.

## Reference Issues/PRs

Fixes #108 

## What does this implement/fix? Explain your changes.

Screenshot 2022-03-12 1 30 50

### CODE REVIEW

File: optuna_dashboard/static/action.ts [hunk 1]
```diff
@@ -54,7 +54,8 @@ export const actionCreator = () => {
         setStudyDetails(newVal)
       })
       .catch((err) => {
-        enqueueSnackbar(`Failed to fetch study (id=${studyId})`, {
+        const reason = err.response?.data.reason
+        enqueueSnackbar(`Failed to fetch study (reason=${reason})`, {
```
Comment (c-bata) [inline optuna_dashboard/static/action.ts:58]: Screenshot 2022-03-12 2 12 18
